apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: chat-app
spec:
  type: NodePort
  selector:
    app: emqx
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    nodePort: 31883

  - name: dashboard
    port: 18083
    targetPort: 18083
    nodePort: 31803